steps:

#
# Extract the cache
#
# The gradle build cache is stored as a tarball in Google Cloud Storage to
# make builds faster.
#
# After extracting the cache to the /build_cache directory, we need to supply
# that to gradle, and include the volume in steps that require the cache.
#
- name: 'gcr.io/cloud-builders/gsutil'
  id: copy_build_cache
  # we use rsync and not cp so that this step doesn't fail the first time it's run
  args: ['rsync', 'gs://${_CACHE_BUCKET}/', '/build_cache']
  volumes:
  - name: 'build_cache'
    path: '/build_cache'

- name: 'gcr.io/$PROJECT_ID/tar'
  id: extract_build_cache
  waitFor: ['copy_build_cache']
  # This might fail the first time, but that's okay
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    tar xpzf /build_cache/cache.tgz -C /build_cache || echo "No cache found."
  volumes:
  - name: 'build_cache'
    path: '/build_cache'

#
# Build the project
#
- name: 'gcr.io/$PROJECT_ID/android:29-ndk-r17b'
  id: build
  args: ["./gradlew", "assembleDebug"]
  env:
  - 'TERM=dumb'
  - 'JAVA_TOOL_OPTIONS="-Xmx3g"'
  - 'GRADLE_USER_HOME=/build_cache/.gradle'
  - 'GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=32 -Dkotlin.incremental=false -Dorg.gradle.caching=true"'
  - 'BRANCH_NAME=$BRANCH_NAME'
  waitFor: ['extract_build_cache']
  volumes:
  - name: 'build_cache'
    path: '/build_cache'

#
# Option
#

# Specify GCB machine type
# May incur charge https://cloud.google.com/cloud-build/pricing
#options:
# https://cloud.google.com/cloud-build/docs/api/reference/rest/Shared.Types/MachineType
#   machineType: 'UNSPECIFIED'  

timeout: 1800s
